services:
  # 1. The Spring Boot Backend
  - type: web
    name: health-office-backend
    runtime: docker
    rootDir: backend
    region: frankfurt
    plan: free
    envVars:
      # We EXPLICITLY override Render's auto-injected variable with the correct JDBC format
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: health-office-db
          property: connectionString
        value: jdbc:%s 
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        generateValue: true
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: health-office-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: health-office-db
          property: password

  # 2. The Flutter Web Frontend
  - type: web
    name: health-office-portal
    runtime: docker
    dockerContext: .
    dockerfilePath: Dockerfile.web
    region: frankfurt
    plan: free

databases:
  - name: health-office-db
    plan: free
    region: frankfurt
